### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Nibbles#8]
If possible, please consider verifying this Flatpak.

Here is more info about verified apps: https://flathub.org/about

**Comment by bcorby** [comment]
I tried doing this but failed. The developer portal doesn't show me any apps.

**Comment by AsciiWolf** [comment]
That's strange. It should be [here](https://flathub.org/apps/manage/org.gnome.Nibbles). Are you logging in to Flathub using the correct account?

**Comment by bcorby** [comment]
I log in using GNOME GitLab, which works fine.
I have attached a screen shot of what I see when I go to 
https://flathub.org/apps/manage/org.gnome.Nibbles

**Comment by bcorby** [comment]
I don't think my attachment came through. The text on the screen was:


Whoops!




You are unauthorized to view this content.


You might want to retry or go back [home](https://flathub.org/).

**Comment by AsciiWolf** [comment]
Did you try logging in using your GitHub account?

**Comment by bcorby** [comment]
I just tried using GitHub login and I had the same result.

Please give me a little bit of background. How does flathub detect I'm 
the maintainer of GNOME Nibbles?

**Comment by AsciiWolf** [comment]
@barthalion Any idea?

**Comment by AsciiWolf** [comment]
Ah, I think I see the problem now. You most likely do not (yet) have push rights access to this repository.

**Comment by AsciiWolf** [comment]
@barthalion Any chance you could add @bcorby the push rights?

**Comment by barthalion** [comment]
Done. Please note that https://gitlab.gnome.org/GNOME/gnome-nibbles/-/blob/master/gnome-nibbles.doap?ref_type=heads should list @bcorby as the first maintainer, and we need to add additional mapping from org.gnome.Nibbles to GNOME/gnome-nibbles. Please open a separate issue for the latter at https://github.com/flathub/website/.

**Comment by bcorby** [comment]
I have updated the doap file.

**Comment by barthalion** [comment]
I have pushed a commit with the mapping to gnome-nibbles. Please give it a shot in 1h or so; log in to flathub.org with your GNOME GitLab account, then navigate to "Developer portal" after clicking your avatar in the top-right corner.

**Comment by bcorby** [comment]
On the page https://flathub.org/developer-portal I see "No apps to show." under Authored apps.
The page https://flathub.org/apps/manage/org.gnome.Nibbles says "You are unauthorized to view this content."

**Comment by barthalion** [comment]
Please connect your GitHub account at https://flathub.org/settings as well.

**Comment by bcorby** [comment]
I clicked Log in with Git Hub under Link More Accounts, logged in and then got a continuous rotation blue semi-circle. I have tried these steps from several machines and all get exactly the same result.
I checked but I still see "No apps to show." under Authored apps.

**Comment by bcorby** [comment]
I still don't have access to:
https://flathub.org/apps/manage/org.gnome.Nibbles
I get
```
Whoops!

You are unauthorized to view this content.
You might want to retry or go back [home](https://flathub.org/).
```
